### ISSUE TITLE
Comments loading is a bit slow

### ISSUE THREAD

**Issue by tdamsma** [quasarframework/quasar-hackernews#3]
Comments are the life and blood of HN, at least for me. Using this demo comment loading takes noticeably longer than loading a complete new page on the "real" hackernews. How about pre-fetching the first 10 comments in the background for every thread shown on the main page?

**Comment by rstoenescu** [comment]
Hi,

This is only a demo for Quasar working with server side rendering so that developers can learn how they can do SSR. Not a full fledged website to replace the official hackernews so the features of the app itself are irrelevant -- as this is not the purpose in itself.
